### PR TITLE
Add helper for word wrapping

### PR DESCRIPTION
**Pull request by fuadsaud**
Just kicking off the implementation helpers (mainly for discussing conventions and how to lay things out).

PS.: I still need to document it.

### CODE REVIEW

**Comment by joneslee85** [comment]
Hey @fuadsaud, thanks for this PR and sorry for late reply.

We are trying to avoid helpers that are used frequently, I myself don't use Word Wrapping much so I would love to hear opinions from others on this.

cc @lotus/core-team

**Comment by jodosha** [comment]
I'd say to postpone this. I want the first release to be about HTML generators and forms. We can add this useful feature later. Thank you! :+1:

**Comment by joneslee85** [comment]
Let's bring the discussion back, I don't want to let this PR hung-over

**Comment by fuadsaud** [comment]
Hi there.

I have been been absent from the discussion since last year and I while I appreciate what work being done with Lotus, I don't have any intent to get involved in the project as of now - and this code is probably not following current best practices/patterns in the Lotus codebase; therefore, feel free to checkout, rework and merge any work I've done here.

**Comment by joneslee85** [comment]
@fuadsaud thanks for the update

**Comment by jodosha** [comment]
@fuadsaud Thanks for the explanation and your effort, I'm closing this for the time being. All the best :+1:

**Pull request closed without merging**
